version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend
    restart: always
    environment:
      - FLASK_APP=backend/app.py
      - FLASK_ENV=development
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    command: ["sh", "-c", "flask db upgrade && gunicorn --bind 0.0.0.0:5000 app:app"]

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

  db:
    image: postgres:13
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: arya_admin_db
      POSTGRES_PASSWORD: Gab5i9A6k8Ry
      POSTGRES_DB: arya_web_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
