version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: arya_admin_db
      POSTGRES_PASSWORD: Gab5i9A6k8Ry
      POSTGRES_DB: arya_web_db
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      FLASK_ENV: production
      DATABASE_URL: postgresql://arya_admin_db:Gab5i9A6k8Ry@db:5432/arya_web_db
      MAIL_SERVER: smtp.gmail.com
      MAIL_PORT: "587"
      MAIL_USE_TLS: "True"
      MAIL_USERNAME: roboticdock@gmail.com
      MAIL_PASSWORD: "eaqttnictahosgro"
      MAIL_DEFAULT_SENDER: roboticdock@gmail.com
    depends_on:
      - db
    ports:
      - "5000:5000"
