services:
  - type: web
    name: arya-architect-backend
    env: docker
    plan: free
    dockerfilePath: ./backend/Dockerfile
    buildCommand: ""
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        value: postgres://admin_db:Gab5i9A6k8Ry@db:5432/arya_web_db
      - key: MAIL_SERVER
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: "587"
      - key: MAIL_USE_TLS
        value: "True"
      - key: MAIL_USERNAME
        value: roboticdock@gmail.com
      - key: MAIL_PASSWORD
        value: eaqttnictahosgro
      - key: MAIL_DEFAULT_SENDER
        value: roboticdock@gmail.com

  - type: web
    name: arya-architect-frontend
    env: docker
    plan: free
    dockerfilePath: ./frontend/Dockerfile
    buildCommand: ""
